service: troubleshooting
frameworkVersion: '3'

provider:
  name: aws
  runtime: java11
  stage: production
  region: eu-central-1
  timeout: 15
  memorySize: 1024
  logRetentionInDays: 7

package:
  artifact: target/Function-1.0.jar

functions:
  test-logging:
    handler: helloworld.App
